# .github/workflows/deploy.yml
name: Deploy to Google Cloud Run vuejs
on:
  push:
    paths: 
      - "Phase 2/**"
      
jobs:
  deploy:
    name: Deploying
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Build and push image to Google Container Registry
      - name: Setting up
        uses: google-github-actions/setup-gcloud@v0
        with:
          version: '286.0.0'
          service_account_key: ${{ secrets.GCP_SA_KEY_JSON }}
          service_account_email: "github-actions@bcccodingchallenge.iam.gserviceaccount.com"
          project_id: bcccodingchallenge

      - name: Building
        run: |-
          cd "Phase 2/demo"
          gcloud builds submit --tag gcr.io/bcccodingchallenge/vuejs-image
      # Setup gcloud CLI
      - name: Deploy
        uses: google-github-actions/deploy-cloudrun@v0
        with:
          service: vuejs-image
          image: gcr.io/bcccodingchallenge/vuejs-image
          region: europe-central2
          credentials: ${{ secrets.GCP_SA_KEY_JSON }}
          project_id: bcccodingchallenge
